/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'consulta-facturas': RouteRecordInfo<'consulta-facturas', '/consulta-facturas', Record<never, never>, Record<never, never>>,
    'dashboards-crm': RouteRecordInfo<'dashboards-crm', '/dashboards/crm', Record<never, never>, Record<never, never>>,
    'gastos': RouteRecordInfo<'gastos', '/gastos', Record<never, never>, Record<never, never>>,
    'ingresos': RouteRecordInfo<'ingresos', '/ingresos', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'notificaciones': RouteRecordInfo<'notificaciones', '/notificaciones', Record<never, never>, Record<never, never>>,
    'parametros-comprobantes': RouteRecordInfo<'parametros-comprobantes', '/parametros/comprobantes', Record<never, never>, Record<never, never>>,
    'parametros-proveedores': RouteRecordInfo<'parametros-proveedores', '/parametros/proveedores', Record<never, never>, Record<never, never>>,
    'parametros-tipos-gasto': RouteRecordInfo<'parametros-tipos-gasto', '/parametros/tipos-gasto', Record<never, never>, Record<never, never>>,
    'procesos-arqueo': RouteRecordInfo<'procesos-arqueo', '/procesos/arqueo', Record<never, never>, Record<never, never>>,
    'procesos-cierre': RouteRecordInfo<'procesos-cierre', '/procesos/cierre', Record<never, never>, Record<never, never>>,
    'procesos-historial-arqueos': RouteRecordInfo<'procesos-historial-arqueos', '/procesos/historial-arqueos', Record<never, never>, Record<never, never>>,
    'procesos-historial-cierres': RouteRecordInfo<'procesos-historial-cierres', '/procesos/historial-cierres', Record<never, never>, Record<never, never>>,
    'procesos-liquidacion': RouteRecordInfo<'procesos-liquidacion', '/procesos/liquidacion', Record<never, never>, Record<never, never>>,
    'reportes-gastos': RouteRecordInfo<'reportes-gastos', '/reportes/gastos', Record<never, never>, Record<never, never>>,
    'reportes-ingresos-egresos': RouteRecordInfo<'reportes-ingresos-egresos', '/reportes/ingresos-egresos', Record<never, never>, Record<never, never>>,
    'reportes-mensual': RouteRecordInfo<'reportes-mensual', '/reportes/mensual', Record<never, never>, Record<never, never>>,
    'reportes-persona': RouteRecordInfo<'reportes-persona', '/reportes/persona', Record<never, never>, Record<never, never>>,
    'reportes-proveedor': RouteRecordInfo<'reportes-proveedor', '/reportes/proveedor', Record<never, never>, Record<never, never>>,
    'reportes-semanal': RouteRecordInfo<'reportes-semanal', '/reportes/semanal', Record<never, never>, Record<never, never>>,
    'reportes-tipo-gasto': RouteRecordInfo<'reportes-tipo-gasto', '/reportes/tipo-gasto', Record<never, never>, Record<never, never>>,
    'seguridad-permisos': RouteRecordInfo<'seguridad-permisos', '/seguridad/permisos', Record<never, never>, Record<never, never>>,
    'seguridad-roles': RouteRecordInfo<'seguridad-roles', '/seguridad/roles', Record<never, never>, Record<never, never>>,
    'seguridad-usuarios': RouteRecordInfo<'seguridad-usuarios', '/seguridad/usuarios', Record<never, never>, Record<never, never>>,
  }
}
