import { Request, Response } from 'express'
import bcrypt from 'bcryptjs'
import { RowDataPacket, ResultSetHeader } from 'mysql2'
import { db } from '../config/db'

const fail = (res: Response, error: unknown) => res.status(400).json({ message: error instanceof Error ? error.message : 'Error de seguridad.' })
export const usuarios = async (_: Request, res: Response) => { const [r] = await db.query<RowDataPacket[]>(`SELECT u.id,u.nombre_completo,u.email,u.rol_id,u.empresa_id,e.nombre empresa,d.nombre departamento,ro.nombre rol FROM usuarios u JOIN roles ro ON ro.id=u.rol_id LEFT JOIN empresas e ON e.id=u.empresa_id LEFT JOIN departamentos d ON d.id=u.departamento_id ORDER BY u.nombre_completo`); res.json(r) }
export const crearUsuario = async (req: Request, res: Response) => { try { const { nombre_completo,email,password,rol_id,empresa_id=null,departamento_id=null }=req.body;if(!nombre_completo||!email||String(password).length<8||!Number(rol_id))throw new Error('Completa nombre, correo, contraseña de 8 caracteres y rol.');const hash=await bcrypt.hash(password,10);const[r]=await db.query<ResultSetHeader>(`INSERT INTO usuarios (rol_id,empresa_id,departamento_id,nombre_completo,email,password) VALUES (?,?,?,?,?,?)`,[rol_id,empresa_id||null,departamento_id||null,String(nombre_completo).slice(0,150),String(email).toLowerCase().slice(0,150),hash]);res.status(201).json({id:r.insertId})}catch(e){fail(res,e)} }
export const actualizarUsuario = async (req: Request,res:Response)=>{try{const {nombre_completo,email,rol_id,password,empresa_id=null,departamento_id=null}=req.body;const p:any[]=[nombre_completo,email,rol_id,empresa_id||null,departamento_id||null];let sql=`UPDATE usuarios SET nombre_completo=?,email=?,rol_id=?,empresa_id=?,departamento_id=?`;if(password){if(String(password).length<8)throw new Error('La contraseña debe tener 8 caracteres.');sql+=`,password=?`;p.push(await bcrypt.hash(password,10))}p.push(req.params.id);await db.query(sql+' WHERE id=?',p);res.json({message:'Usuario actualizado.'})}catch(e){fail(res,e)} }
export const permisos = async (_:Request,res:Response)=>{const[r]=await db.query<RowDataPacket[]>(`SELECT * FROM permisos ORDER BY modulo,accion`);res.json(r)}
export const crearPermiso=async(req:Request,res:Response)=>{try{const{modulo,accion,descripcion=''}=req.body;if(!modulo||!accion)throw new Error('Módulo y acción son obligatorios.');const[r]=await db.query<ResultSetHeader>('INSERT INTO permisos (modulo,accion,descripcion) VALUES (?,?,?)',[modulo,accion,descripcion]);res.status(201).json({id:r.insertId})}catch(e){fail(res,e)}}
export const roles=async(_:Request,res:Response)=>{const[r]=await db.query<RowDataPacket[]>(`SELECT r.*,e.nombre empresa,d.nombre departamento,COALESCE(JSON_ARRAYAGG(rp.permiso_id),JSON_ARRAY()) permiso_ids FROM roles r LEFT JOIN empresas e ON e.id=r.empresa_id LEFT JOIN departamentos d ON d.id=r.departamento_id LEFT JOIN rol_permisos rp ON rp.rol_id=r.id GROUP BY r.id ORDER BY r.nombre`);res.json(r)}
export const organizacion=async(_:Request,res:Response)=>{const[empresas]=await db.query<RowDataPacket[]>('SELECT id,nombre,estado FROM empresas ORDER BY id');const[departamentos]=await db.query<RowDataPacket[]>('SELECT id,empresa_id,nombre,estado FROM departamentos ORDER BY empresa_id,nombre');res.json({empresas,departamentos})}
export const guardarRol=async(req:Request,res:Response)=>{const c=await db.getConnection();try{const{nombre,descripcion='',estado=true,permiso_ids=[]}=req.body;if(!nombre)throw new Error('El nombre es obligatorio.');await c.beginTransaction();let id=Number(req.params.id);if(id)await c.query('UPDATE roles SET nombre=?,descripcion=?,estado=?,actualizado_en=NOW() WHERE id=?',[nombre,descripcion,estado?1:0,id]);else{const[r]=await c.query<ResultSetHeader>('INSERT INTO roles (nombre,descripcion,estado,creado_en,actualizado_en) VALUES (?,?,?,NOW(),NOW())',[nombre,descripcion,estado?1:0]);id=r.insertId}await c.query('DELETE FROM rol_permisos WHERE rol_id=?',[id]);for(const permiso of permiso_ids)await c.query('INSERT INTO rol_permisos (rol_id,permiso_id) VALUES (?,?)',[id,permiso]);await c.commit();res.json({id})}catch(e){await c.rollback();fail(res,e)}finally{c.release()}}
