<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { apiProcesos, solicitudId } from '@/utils/procesos'
import HistorialProcesos from '@/components/procesos/HistorialProcesos.vue'
const fondos=ref<any[]>([]);const fondoId=ref<number|null>(null);const resumen=ref<any>(null);const monto=ref<number|null>(null);const receptor=ref('');const comprobante=ref('');const observaciones=ref('');const error=ref('');const ok=ref('');const loading=ref(false)
const consultar=async()=>{if(!fondoId.value)return;try{resumen.value=await apiProcesos(`/resumen/${fondoId.value}`);monto.value=Number(resumen.value.saldoLibros/100)}catch(e:any){error.value=e.message}}
const liquidar=async()=>{if(!fondoId.value||!confirm('La liquidación es definitiva. ¿Confirmar?'))return;loading.value=true;try{const r=await apiProcesos('/liquidacion',{method:'POST',body:JSON.stringify({fondo_id:fondoId.value,solicitud_id:solicitudId(),monto_remanente:monto.value,receptor_nombre:receptor.value,comprobante_entrega:comprobante.value,observaciones:observaciones.value})});ok.value=`Liquidación #${r.id} guardada.`}catch(e:any){error.value=e.message}finally{loading.value=false}}
onMounted(async()=>{try{fondos.value=(await apiProcesos('/fondos')).filter((f:any)=>f.estado==='cerrado')}catch(e:any){error.value=e.message}})
</script>
<template><VRow><VCol cols="12"><VCard><VCardItem><VCardTitle>Liquidación final</VCardTitle></VCardItem><VCardText><VAlert v-if="error" type="error">{{error}}</VAlert><VAlert v-if="ok" type="success">{{ok}}</VAlert><VSelect v-model="fondoId" :items="fondos" item-title="id" item-value="id" label="Fondo cerrado" @update:model-value="consultar"/><p v-if="resumen">Saldo remanente: <b>Q{{Number(resumen.saldoLibros/100).toFixed(2)}}</b></p><VTextField v-model.number="monto" type="number" label="Monto del remanente entregado"/><VTextField v-model="receptor" label="Nombre de quien recibe"/><VTextField v-model="comprobante" label="Número de recibo o comprobante"/><VTextarea v-model="observaciones" label="Observaciones"/><VBtn color="primary" :loading="loading" @click="liquidar">Confirmar liquidación</VBtn></VCardText></VCard></VCol><VCol cols="12"><HistorialProcesos tipo="liquidacion" titulo="Historial de Liquidaciones" /></VCol></VRow></template>
